title: Site

columns:
  - width: 1/2
    sections:
      pages:
        type: pages
        headline: Stránky
        templates:
          - homepage
          - blog
          - vypocet
          - investicne-platformy
          - investicne-nastroje
        sortable: true

  - width: 1/2
    sections:
      posts:
        type: pages
        headline: Články
        templates:
          - blogpost
        sortable: true
      instruments:
        type: pages
        headline: Nástroje
        templates:
          - investicne-nastroje
